name: CI

on:
  push:
    branches:
    - master
    tags:
    - v*
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
        - os: windows-latest
          runtime: win-x64
        - os: macos-latest
          runtime: osx-x64
        - os: ubuntu-latest
          runtime: linux-x64

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install .NET
      uses: actions/setup-dotnet@v1

    - name: Upload coverage
      uses: codecov/codecov-action@v1

    - name: Publish
      run: dotnet publish --configuration Release --runtime ${{ matrix.runtime }} --self-contained --output build/artifacts/${{ matrix.runtime }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.runtime }}
        path: build/artifacts/${{ matrix.runtime }}

  publish:
    needs: build

    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    runs-on: windows-latest

    steps:
    - name: Download Artifacts win-x64
      uses: actions/download-artifact@v1
      with:
        name: win-x64

    - name: Download Artifacts osx-x64
      uses: actions/download-artifact@v1
      with:
        name: osx-x64

    - name: Download Artifacts linux-x64
      uses: actions/download-artifact@v1
      with:
        name: linux-x64

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: "## Instructions"
        draft: false
        prerelease: true

    # TODO: Upload Release Assets
    # using actions/upload-a-release-asset